//login
const LOGIN_DATA_ACTION = 'LOGIN_DATA_ACTION'

//home
const DEFAULT_DATA_ACTION = 'DEFAULT_DATA_ACTION'
const ADD_DATA_ACTION = 'ADD_DATA_ACTION'
const EDIT_DATA_ACTION = 'EDIT_DATA_ACTION'
const DELETE_DATA_ACTION = 'DELETE_DATA_ACTION'
export {
    LOGIN_DATA_ACTION,
    DEFAULT_DATA_ACTION,
    ADD_DATA_ACTION,
    EDIT_DATA_ACTION,
    DELETE_DATA_ACTION
}