//login
const LOGIN_DATA = 'LOGIN_DATA'

//home
const DEFAULT_DATA = 'DEFAULT_DATA'
const CANCEL_STATUS = 'CANCEL_STATUS'
const SHOW_STATUS = 'SHOW_STATUS'
const EDIT_SHOW_STATUS = 'EDIT_SHOW_STATUS'
export {
    LOGIN_DATA,
    DEFAULT_DATA,
    CANCEL_STATUS,
    SHOW_STATUS,
    EDIT_SHOW_STATUS
}